image: ubuntu/lts
packages:
    - julia
tasks:
    - build: |
        cd PlateMotionRequests.jl
        julia --project -e 'using Pkg; Pkg.instantiate()'
    - test: |
        cd PlateMotionRequests.jl
        julia --project test/runtests.jl
