name = "PlateMotionRequests"
uuid = "d13234e1-ff52-466f-9770-1615bbbda812"
authors = ["adigitoleo <adigitoleo@dissimulo.com>"]
version = "3.1.2"
keywords = ["geophysics"]
license = "0BSD"
desc = "Request tectonic plate motion data for various Earth rotation models in Julia"

[compat]
julia = "1"
DataStructures = "0.18.12"
DocStringExtensions = "0.8.6"
HTTP = "0.9.17"
NCDatasets = "0.12.4"
TypedTables = "1.4.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
TypedTables = "9d95f2ec-7b3d-5a63-8d20-e2491e220bb9"
