#!/bin/python3
# Copy or link this script into .git/hooks/
# It runs automatically in the project root directory (parent of .git/ directory).
import subprocess
import pathlib

# Run tests.
if pathlib.Path("test/runtests.jl").is_file():
    subprocess.run(["julia", "--project", "test/runtests.jl"], check=True)

# Check if last tag and version from Project.toml match.
LAST_TAG = subprocess.run(
    ["git", "describe", "--tags", "--abbrev=0"], check = True, capture_output = True,
).stdout.decode().strip()
print(f"Last tag: {LAST_TAG}")
with open("Project.toml") as file:
    for line in file:
        if line.startswith("version"):
            TOML_VERSION = line.split("=")[1].strip().strip('"')
            break
print(f"Project.toml version: v{TOML_VERSION}")
if LAST_TAG != f"v{TOML_VERSION}":
    print("Stopping commit: last git tag and Project.toml version don't match.")
    print("Use git commit --no-verify to commit anyway if this is a release.")
    print("Remember to create the tag afterwards.")
    raise SystemExit(1)
