name: Continuous Integration (Windows)

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - next
      - dev

jobs:
  test:
    name: Run tests (Windows)
    runs-on: windows-latest
    steps:
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
          arch: x86
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
